CREATE TABLE IF NOT EXISTS memories (
  id VARCHAR(64) PRIMARY KEY,
  content TEXT NOT NULL,
  embedding JSON NULL,
  content_hash VARCHAR(64) NOT NULL,
  type VARCHAR(32) NULL,
  kinds JSON NULL,
  scope VARCHAR(32) NOT NULL DEFAULT 'user',
  state VARCHAR(32) NOT NULL DEFAULT 'creating',
  metadata JSON NULL,
  agent_id VARCHAR(128) NULL,
  session_id VARCHAR(128) NULL,
  source VARCHAR(128) NULL,
  version INT NOT NULL DEFAULT 1,
  store_count INT NOT NULL DEFAULT 0,
  use_count INT NOT NULL DEFAULT 0,
  last_accessed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_memories_content_hash (content_hash),
  KEY idx_memories_state (state),
  KEY idx_memories_type (type),
  KEY idx_memories_agent_id (agent_id),
  KEY idx_memories_session_id (session_id)
);
