CREATE TABLE IF NOT EXISTS ingest_jobs (
  id VARCHAR(64) PRIMARY KEY,
  content TEXT NOT NULL,
  type VARCHAR(32) NULL,
  kinds JSON NULL,
  scope VARCHAR(32) NOT NULL DEFAULT 'user',
  mode VARCHAR(32) NOT NULL,
  state VARCHAR(32) NOT NULL DEFAULT 'pending',
  metadata JSON NULL,
  agent_id VARCHAR(128) NULL,
  session_id VARCHAR(128) NULL,
  source VARCHAR(128) NULL,
  execute_count INT NOT NULL DEFAULT 0,
  next_run_at TIMESTAMP NULL,
  locked_at TIMESTAMP NULL,
  worker_id VARCHAR(128) NULL,
  last_error TEXT NULL,
  result_memory_ids JSON NULL,
  result_summary TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ingest_jobs_state (state),
  KEY idx_ingest_jobs_mode (mode),
  KEY idx_ingest_jobs_worker_id (worker_id),
  KEY idx_ingest_jobs_next_run_at (next_run_at)
);
